SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
ASPECT_RATIO = 4/3
SCREEN_TITLE = "Super XOR Bros"

CHARACTER_SCALING = 0.25
TILE_SCALING = 0.5
COIN_SCALING = 0.15
BLOCK_SIZE = 16 # in pixels
MAP_HEIGHT = 13 # in blocks

PLAYER_MOVEMENT_SPEED = 1
PLAYER_JUMP_SPEED = 6

# Tile Layer names
LAYER_NAME_WALLS = "Walls"
LAYER_NAME_DECOR = "Decoration"
LAYER_NAME_PLAYER = "Player"
LAYER_NAME_BRICKS = "Bricks"
LAYER_NAME_COINS = "Coins"
LAYER_NAME_BRICK_TRIGGERS = "Brick Triggers"

# Object Layer names
OBJECT_LAYER_NAME_BRICKS = "Bricks"

TRIGGER_MARGIN = 0.5

PLAYER_START_X = 2
PLAYER_START_Y = 3

RIGHT_FACING = 0
LEFT_FACING = 1

COIN_TEXTURE_DELAY = 10