SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
ASPECT_RATIO = 4/3
SCREEN_TITLE = "Super XOR Bros"

CHARACTER_SCALING = 0.25
TILE_SCALING = 0.5
MAP_HEIGHT = 13 # in blocks

PLAYER_MOVEMENT_SPEED = 1
PLAYER_JUMP_SPEED = 6

LAYER_NAME_WALLS = "Walls"
LAYER_NAME_DECOR = "Decoration"
LAYER_NAME_PLAYER = "Player"

PLAYER_START_X = 2
PLAYER_START_Y = 3

RIGHT_FACING = 0
LEFT_FACING = 1